config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :result_colors

  root to: 'problem_lists#index'

  resources :results

  resources :problems

  resources :problem_lists do
    collection do
      get 'logout', action: :logout
    end
  end

  resources :users do
    collection do
      get 'sign_in', action: :show_sign_in
      post 'try_enter', action: :try_enter
    end
  end

  mathjax 'mathjax'

  match '/places' => 'places#show', via: [:get, :post]
  match '/update_places_now' => 'places#update_now', via: [:get, :post]

  match '*path', via: :all, to: 'pages#error_404'

end

app/models/problem_list.rb
class ProblemList < ActiveRecord::Base
  validates :title, presence: true,
            length: {minimum: 1},
            uniqueness: true

  #description


  has_many :problems


end

app/controllers/problem_lists_controller.rb
class ProblemListsController < ApplicationController
  before_action :check_user, except: [:show, :index]
  before_action :check_admin, except: [:show, :index, :logout]
  before_action :set_problem_list, only: [:show, :edit, :update, :destroy]

  def index
    @problem_lists = ProblemList.all
  end

  def show
  end

  def new
    @problem_list = ProblemList.new
  end

  def edit
  end

  def logout
    reset_session
    redirect_to problem_lists_path
  end

  def create
    @problem_list = ProblemList.new(problem_list_params)

    respond_to do |format|
      if @problem_list.save
        format.html { redirect_to @problem_list, notice: 'Problem list was successfully created.' }
        format.json { render :show, status: :created, location: @problem_list }
      else
        format.html { render :new }
        format.json { render json: @problem_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @problem_list.update(problem_list_params)
        format.html { redirect_to @problem_list, notice: 'Problem list was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem_list }
      else
        format.html { render :edit }
        format.json { render json: @problem_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @problem_list.destroy
    respond_to do |format|
      format.html { redirect_to problem_lists_url, notice: 'Problem list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_problem_list
    @problem_list = ProblemList.find(params[:id])
  end

  def problem_list_params
    params.require(:problem_list).permit(:title, :description)
  end


end

app/helpers/problem_lists_helper.rb
module ProblemListsHelper

  def problem_lists_count
    ProblemList.all.count
  end

end

app/views/problem_lists/_form.html.erb
<%= form_for(@problem_list) do |f| %>
    <% if @problem_list.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@problem_list.errors.count, "error") %> prohibited this problem_list from being
                saved:</h2>

            <ul>
                <% @problem_list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title, :autofocus => true %>
    </div>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/problem_lists/edit.html.erb
<h1>Editing problem_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem_list %> |
<%= link_to 'Back', problem_lists_path %>

app/views/problem_lists/index.html.erb
<% index_i = 0 %>
<% @problem_lists.reverse_each do |problem_list| %>
    <% case (index_i % 3) %>
<% when 0 %>
        <% this_table_align = "left_problem_list_align" %>
    <% when 1 %>
        <% this_table_align = "middle_problem_list_align" %>
    <% else %>
        <% this_table_align = "right_problem_list_align" %>
    <% end %>

    <% unless adminned %>
        <a href="<%= problem_list_path(problem_list) %>" class="table_link">
    <% end %>

    <table class="table_problem_list_short_view <%= this_table_align %>" style="top: <%= (index_i / 3) * 230 %>px">
        <tr>
            <td colspan="7" align="center" class="problem_list_name">
                <%= link_to_if adminned, problem_list.title, problem_list, class: "td_link" %>
            </td>
        </tr>
        <tr>
            <td></td>
            <% problem_list.problems.each do |problem| %>
                <td align="center" class="problem_number">
                    <%= link_to_if adminned, ("&nbsp;".html_safe + problem.number.to_s + "&nbsp;".html_safe), problem_path(problem), class: "td_link" %>
                </td>
            <% end %>
        </tr>
        <% User.all.each do |user| %>
            <% unless user.name == "dima" %>
                <tr>
                    <td align="center" class="user_name">
                        <%= link_to_if adminned, ("&nbsp;".html_safe + user.name + "&nbsp;".html_safe), user_path(user), class: "td_link" %>
                    </td>
                    <% problem_list.problems.each do |problem| %>
                        <% cur = problem.results.select { |result| result.user_id == user.id } %>
                        <% if cur.count > 0 %>
                            <% result = cur.first %>
                            <% td_color = result.get_color %>
                            <td align="center" class="result_status" style="background-color: <%= "#%02x%02x%02x" % [td_color.red, td_color.green, td_color.blue] %>">
                                <%= link_to_if adminned, result.status, result_path(result), class: "td_link" %>
                            </td>
                        <% else %>
                            <td align="center" class="result_status" style="background-color: grey">
                                <%= link_to_if adminned, "&nbsp;".html_safe, new_result_path(problem_id: problem.id, user_id: user.id), class: "td_link" %>
                            </td>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
        <% end %>
        <tr class="blank_tr"></tr>

    </table>

    <% unless adminned %>
        </a>
    <% end %>

    <% index_i += 1 %>
<% end %>

<style>
    .main_body {
        min-height: <%= (((index_i - 1) / 3 + 1) * 230 + 130).to_s + "px;" %>
    }
</style>


<a href="<%= new_answer_path %>" class="add_button_cross right_bottom">
    <div class="add_button_cross_help1"></div>
    <div class="add_button_cross_help2"></div>
</a>

app/views/problem_lists/new.html.erb
<h1>New problem list</h1>

<%= render 'form' %>

<%= link_to 'Back', problem_lists_path %>

app/views/problem_lists/show.html.erb
<header class="problem_list_header">

    <h1>
        <%= @problem_list.title %>
    </h1>

</header>

<p align="center">
    <%= @problem_list.description %>
</p>

<div>
    <% @problem_list.problems.each do |problem| %>
        <div>
            <span class="plain_bold_text">
                <%= problem.number %>
            </span>
            <span>
                <%= problem.body %>
            </span>
            <% if problem.figure.file? %>
                <div class="centering_image">
                    <%= image_tag problem.figure.url %>
                </div>
            <% end %>
        </div>
        <br>
    <% end %>
</div>

<a href="<%= new_answer_path %>" class="add_button_cross right_float">
    <div class="add_button_cross_help1"></div>
    <div class="add_button_cross_help2"></div>
</a>

<% if adminned %>
    <div class="system_right_console">
        <%= link_to 'New Problem', new_problem_path(problem_list_id: @problem_list.id) %>
        <br>
        <%= link_to 'Edit', edit_problem_list_path(@problem_list) %>
        <br>
        <%= link_to 'Destroy', @problem_list, method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
<% end %>