config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :result_colors

  root to: 'problem_lists#index'

  resources :results

  resources :problems

  resources :problem_lists do
    collection do
      get 'logout', action: :logout
    end
  end

  resources :users do
    collection do
      get 'sign_in', action: :show_sign_in
      post 'try_enter', action: :try_enter
    end
  end

  mathjax 'mathjax'

  match '/places' => 'places#show', via: [:get, :post]
  match '/update_places_now' => 'places#update_now', via: [:get, :post]

  match '*path', via: :all, to: 'pages#error_404'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  validates :number, numericality: true,
            presence: true,
            uniqueness: true


  belongs_to :problem_list
  has_many :results
  has_many :answers


  validate :must_exists

  has_attached_file :figure, :styles => {:medium => "300x300>", :thumb => "100x100>"}, :default_url => nil

  validates_attachment_content_type :figure, :content_type => /\Aimage\/.*\Z/


  private
  def must_exists
    unless ProblemList.exists?(id: self.problem_list)
      errors.add(:problem_list_id, 'must exists')
      return
    end
    errors.add(:problem_list_id, 'can have not more than four problems') if self.problem_list.problems.count >= 5
    if (self.body == nil || self.body.length == 0) && !(self.figure.file?)
      errors.add(:body, 'or image must exists')
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  before_action :check_admin

  before_action :set_problem, only: [:show, :edit, :update, :destroy]


  def index
    @problems = Problem.all
  end

  def show
  end

  def new
    @problem = Problem.new
    if params.has_key?(:problem_list_id)
      @problem.problem_list_id = params[:problem_list_id]
    end
  end

  def edit
  end

  def create
    @problem = Problem.new(problem_params)
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_problem
    @problem = Problem.find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:number, :body, :problem_list_id, :figure)
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_for(@problem, :html => {:multipart => true}) do |f| %>
    <% if @problem.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

            <ul>
                <% @problem.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :number %><br>
        <%= f.number_field :number, :autofocus => true %>
    </div>
    <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </div>
    <div class="field">
        <%= f.file_field :figure %>
    </div>

    <div class="field">
        <%= f.label :problem_list_id %><br>
        <%= f.number_field :problem_list_id %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1>Listing problems</h1>

<table>
    <thead>
    <tr>
        <th>Number</th>
        <th>Body</th>
        <th>Problem list</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @problems.each do |problem| %>
        <tr>
            <td><%= problem.number %></td>
            <td><%= problem.body %></td>
            <td><%= problem.problem_list_id %></td>
            <td><%= link_to 'Show', problem %></td>
            <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
            <td><%= link_to 'Destroy', problem, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p>
    <strong>Number:</strong>
    <%= @problem.number %>
</p>

<p>
    <strong>Body:</strong>
    <%= @problem.body %>
</p>

<p>
    <strong>id:</strong>
    <%= @problem.id %>
</p>

<p>
    <strong>Problem list:</strong>
    <%= link_to @problem.problem_list_id, problem_list_path(@problem.problem_list) %>
    <strong> &nbsp;&nbsp;&nbsp;(
        <%= link_to @problem.problem_list.title, problem_list_path(@problem.problem_list) %> )
    </strong> &nbsp;&nbsp;&nbsp;
    <%= link_to "Add problem here", new_problem_path(problem_list_id: @problem.problem_list) %>
</p>

<%= link_to 'New Result', new_result_path(problem_id: @problem.id) %>
<br>
<br>
<%= link_to 'Destroy', @problem, method: :delete, data: {confirm: 'Are you sure?'} %>
<br>
<br>
<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>
<br>
<br>

<div>
    <% if @problem.figure.file? %>
        <div class="centering_image">
            <%= image_tag @problem.figure.url %>
        </div>
    <% else %>
        <strong>Problem hasn't got a picture.</strong>
    <% end %>
</div>