config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :result_colors

  root to: 'problem_lists#index'

  resources :results

  resources :problems

  resources :problem_lists do
    collection do
      get 'logout', action: :logout
    end
  end

  resources :users do
    collection do
      get 'sign_in', action: :show_sign_in
      post 'try_enter', action: :try_enter
    end
  end

  mathjax 'mathjax'

  match '/places' => 'places#show', via: [:get, :post]
  match '/update_places_now' => 'places#update_now', via: [:get, :post]

  match '*path', via: :all, to: 'pages#error_404'

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  has_attached_file :figure, :styles => {:medium => "300x300>", :thumb => "100x100>"}, :default_url => nil
  validates_attachment_content_type :figure, :content_type => /\Aimage\/.*\Z/


  belongs_to :user

  belongs_to :problem

  validate :must_exists

  private
  def must_exists
    errors.add(:user_id, 'must exists') unless User.exists?(id: self.user)
    errors.add(:problem_id, 'must exists') unless Problem.exists?(id: self.problem)
    if (self.body == nil || self.body.length == 0) && !(self.figure.file?)
      errors.add(:body, 'or image must exists')
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :check_user
  before_action :check_admin, except: [:new, :create]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def edit
  end

  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        #NewAnswerMailer.get_new_answer(@user).deliver_later
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    logger.debug "WWWWW"
    if params.has_key?(:problem_number)
      params[:answer][:problem_id] = Problem.find_by_number(params[:problem_number]).id
    end
    if params.has_key?(:user_name)
      params[:answer][:user_id] = User.find_by_name(params[:user_name]).id
    end
    params.require(:answer).permit(:body, :problem_id, :user_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer, :html => {:multipart => true}) do |f| %>
    <% if @answer.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

            <ul>
                <% @answer.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </div>
    <div class="field">
        <%= f.label :problem_id %><br>
        <%= number_field_tag :problem_number %>
    </div>

    <div class="field">
        <%= f.label :user_id %><br>
        <% if loggined %>
            <%= text_field_tag :user_name, cur_user_name %>
        <% else %>
            <%= text_field_tag :user_name %>
        <% end %>

    </div>
    <div class="field">
        <%= f.label :figure %><br>
        <%= f.file_field :figure %>
    </div>
    <br>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
    <thead>
    <tr>
        <th>Body</th>
        <th>Problem</th>
        <th>User</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @answers.each do |answer| %>
        <tr>
            <td><%= answer.body %></td>
            <td><%= link_to answer.problem.number, problem_path(answer.problem) %></td>
            <td><%= answer.user.name %></td>
            <td><%= link_to 'Show', answer %></td>
            <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
            <td><%= link_to 'Destroy', answer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

app/views/answers/show.html.erb
<p>
    <strong>Body:</strong>
    <%= @answer.body %>
</p>

<p>
    <strong>Problem:</strong>
    <%= @answer.problem_id %>
</p>

<p>
    <strong>User:</strong>
    <%= @answer.user_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>