config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :result_colors

  root to: 'problem_lists#index'

  resources :results

  resources :problems

  resources :problem_lists do
    collection do
      get 'logout', action: :logout
    end
  end

  resources :users do
    collection do
      get 'sign_in', action: :show_sign_in
      post 'try_enter', action: :try_enter
    end
  end

  mathjax 'mathjax'

  match '/places' => 'places#show', via: [:get, :post]
  match '/update_places_now' => 'places#update_now', via: [:get, :post]

  match '*path', via: :all, to: 'pages#error_404'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Math To Us</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body class="main_background">

<header class="container main_header ">
    <a href="<%= problem_lists_path %>" class="main_title">
        <%= image_tag "title.png", class: "main_title_image" %>
    </a>

    <nav class="main_nav_atop_panel">
        <% if loggined %>
            <span class="greetings_header">
                Hello,
                <%= cur_user_name %>
            </span>
            <% if adminned %>
                <%= link_to 'New List', new_problem_list_path, class: "main_header_links" %>
                <%= link_to 'Users', users_path, class: "main_header_links" %>
                <%= link_to 'Colors', result_colors_path, class: "main_header_links" %>
                <%= link_to 'Problems', problems_path, class: "main_header_links" %>
                <%= link_to 'Answers', answers_path, class: "main_header_links" %>
            <% end %>
            <%= link_to(logout_problem_lists_path, class: "main_header_links") do %>
                <div class="delete_button_cross">
                    <div class="delete_button_cross_help1"></div>
                    <div class="delete_button_cross_help2"></div>
                </div>
            <% end %>
        <% else %>
            <%= link_to 'Login', sign_in_users_path, class: "main_header_links" %>
            <%= link_to 'Sign Up', new_user_path, class: "main_header_links" %>
        <% end %>
    </nav>
</header>

<div class="notice_and_alert_line ">
    <div id="notice"><%= notice %></div>
    <div id="alert"><%= alert %></div>
</div>

<div class=" container main_body ">

    <%= yield %>

</div>

<footer class="container main_footer ">
    <div align="center">
        <strong>
            <%= link_to 'Problem Lists', problem_lists_path, class: "main_header_links" %>
        </strong>
    </div>
    \[\int_a^b f(x) dx=F(b)-F(a)\]
</footer>

</body>

</html>

app/views/layouts/plain.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>
</body>

</html>